"""initial payments schema

Revision ID: 975df1b2a9dd
Revises: 
Created: 2026-09-12 10:19:36.110705+00:00

Checklist before merging a migration:
  * Is `downgrade()` correct? You will want it during an incident.
  * Does it lock a large table? ALTER TABLE ... ADD COLUMN with a non-null
    default rewrites the whole table on older Postgres; add the column
    nullable, backfill in batches, then set NOT NULL.
  * Does it drop or rename anything the running code still reads? Deploy the
    code change first, the schema change second.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '975df1b2a9dd'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('payment_intent_id', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('stripe_status', sa.String(length=40), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('amount_received_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='usd', nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=True),
    sa.Column('failure_code', sa.String(length=80), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('succeeded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'succeeded', 'failed', 'cancelled', 'refunded')", name=op.f('ck_payments_status_valid')),
    sa.CheckConstraint('amount_cents > 0', name=op.f('ck_payments_amount_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments')),
    schema='payments'
    )
    op.create_index(op.f('ix_payments_payments_order_id'), 'payments', ['order_id'], unique=False, schema='payments')
    op.create_index(op.f('ix_payments_payments_payment_intent_id'), 'payments', ['payment_intent_id'], unique=True, schema='payments')
    op.create_index('ix_payments_status_created', 'payments', ['status', 'created_at'], unique=False, schema='payments')
    op.create_table('webhook_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('stripe_event_id', sa.String(length=120), nullable=False),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_webhook_events')),
    schema='payments'
    )
    op.create_index(op.f('ix_payments_webhook_events_stripe_event_id'), 'webhook_events', ['stripe_event_id'], unique=True, schema='payments')
    op.create_index('ix_webhook_events_type_time', 'webhook_events', ['event_type', 'received_at'], unique=False, schema='payments')
    op.create_table('refunds',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('stripe_refund_id', sa.String(length=120), nullable=False),
    sa.Column('amount_cents', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('amount_cents > 0', name=op.f('ck_refunds_amount_positive')),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.payments.id'], name=op.f('fk_refunds_payment_id_payments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refunds')),
    sa.UniqueConstraint('stripe_refund_id', name=op.f('uq_refunds_stripe_refund_id')),
    schema='payments'
    )
    op.create_index('ix_refunds_payment', 'refunds', ['payment_id'], unique=False, schema='payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_refunds_payment', table_name='refunds', schema='payments')
    op.drop_table('refunds', schema='payments')
    op.drop_index('ix_webhook_events_type_time', table_name='webhook_events', schema='payments')
    op.drop_index(op.f('ix_payments_webhook_events_stripe_event_id'), table_name='webhook_events', schema='payments')
    op.drop_table('webhook_events', schema='payments')
    op.drop_index('ix_payments_status_created', table_name='payments', schema='payments')
    op.drop_index(op.f('ix_payments_payments_payment_intent_id'), table_name='payments', schema='payments')
    op.drop_index(op.f('ix_payments_payments_order_id'), table_name='payments', schema='payments')
    op.drop_table('payments', schema='payments')
    # ### end Alembic commands ###
