"""initial notifications schema

Revision ID: eda92c469857
Revises: 
Created: 2026-09-12 10:22:11.176476+00:00

Checklist before merging a migration:
  * Is `downgrade()` correct? You will want it during an incident.
  * Does it lock a large table? ALTER TABLE ... ADD COLUMN with a non-null
    default rewrites the whole table on older Postgres; add the column
    nullable, backfill in batches, then set NOT NULL.
  * Does it drop or rename anything the running code still reads? Deploy the
    code change first, the schema change second.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'eda92c469857'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('template', sa.String(length=80), nullable=False),
    sa.Column('to_email', postgresql.CITEXT(), nullable=False),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='queued', nullable=False),
    sa.Column('attempts', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint("status IN ('queued', 'sending', 'sent', 'failed')", name=op.f('ck_notifications_status_valid')),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_notifications_attempts_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    schema='notifications'
    )
    op.create_index('ix_notifications_created', 'notifications', ['created_at'], unique=False, schema='notifications')
    op.create_index('ix_notifications_pending', 'notifications', ['status', 'next_attempt_at'], unique=False, schema='notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_pending', table_name='notifications', schema='notifications')
    op.drop_index('ix_notifications_created', table_name='notifications', schema='notifications')
    op.drop_table('notifications', schema='notifications')
    # ### end Alembic commands ###
