"""email verification tokens

Revision ID: 6ffda8519739
Revises: b092e7a8283d
Created: 2026-09-13 14:35:13.012014+00:00

Checklist before merging a migration:
  * Is `downgrade()` correct? You will want it during an incident.
  * Does it lock a large table? ALTER TABLE ... ADD COLUMN with a non-null
    default rewrites the whole table on older Postgres; add the column
    nullable, backfill in batches, then set NOT NULL.
  * Does it drop or rename anything the running code still reads? Deploy the
    code change first, the schema change second.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '6ffda8519739'
down_revision: str | None = 'b092e7a8283d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verification_tokens',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['auth.users.id'], name=op.f('fk_email_verification_tokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_email_verification_tokens')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_email_verification_tokens_token_hash')),
    schema='auth'
    )
    op.create_index('ix_email_verification_tokens_user', 'email_verification_tokens', ['user_id', 'used_at'], unique=False, schema='auth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_email_verification_tokens_user', table_name='email_verification_tokens', schema='auth')
    op.drop_table('email_verification_tokens', schema='auth')
    # ### end Alembic commands ###
