"""discount codes and fulfilment tracking

Revision ID: 7bd1db3ea3d0
Revises: f3e4ad63a25a
Created: 2026-09-13 13:52:44.606515+00:00

Checklist before merging a migration:
  * Is `downgrade()` correct? You will want it during an incident.
  * Does it lock a large table? ALTER TABLE ... ADD COLUMN with a non-null
    default rewrites the whole table on older Postgres; add the column
    nullable, backfill in batches, then set NOT NULL.
  * Does it drop or rename anything the running code still reads? Deploy the
    code change first, the schema change second.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '7bd1db3ea3d0'
down_revision: str | None = 'f3e4ad63a25a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discount_codes',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', postgresql.CITEXT(), nullable=False),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.Column('min_subtotal_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_uses', sa.Integer(), nullable=True),
    sa.Column('used_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint("kind <> 'percent' OR value <= 10000", name=op.f('ck_discount_codes_percent_within_range')),
    sa.CheckConstraint("kind IN ('percent', 'fixed')", name=op.f('ck_discount_codes_kind_valid')),
    sa.CheckConstraint('max_uses IS NULL OR used_count <= max_uses', name=op.f('ck_discount_codes_uses_within_limit')),
    sa.CheckConstraint('used_count >= 0', name=op.f('ck_discount_codes_used_count_non_negative')),
    sa.CheckConstraint('value > 0', name=op.f('ck_discount_codes_value_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_discount_codes')),
    schema='orders'
    )
    op.create_index('ix_discount_codes_active', 'discount_codes', ['is_active', 'ends_at'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_discount_codes_code'), 'discount_codes', ['code'], unique=True, schema='orders')
    op.add_column('orders', sa.Column('discount_cents', sa.Integer(), server_default='0', nullable=False), schema='orders')
    op.add_column('orders', sa.Column('discount_code', sa.String(length=40), nullable=True), schema='orders')
    op.add_column('orders', sa.Column('carrier', sa.String(length=60), nullable=True), schema='orders')
    op.add_column('orders', sa.Column('tracking_number', sa.String(length=120), nullable=True), schema='orders')
    op.add_column('orders', sa.Column('shipped_at', sa.DateTime(timezone=True), nullable=True), schema='orders')
    # ### end Alembic commands ###

    # --- CHECK constraints, added by hand ------------------------------------
    #
    # Alembic's autogenerate does not diff CHECK constraints, so a change to
    # one is silently omitted. The total formula gained a discount term, and
    # without this the old constraint would reject every discounted order at
    # insert time - with an integrity error rather than anything readable.
    op.drop_constraint("ck_orders_total_is_sum_of_parts", "orders", schema="orders")
    op.create_check_constraint(
        "total_is_sum_of_parts",
        "orders",
        "total_cents = subtotal_cents - discount_cents + tax_cents + shipping_cents",
        schema="orders",
    )
    op.create_check_constraint(
        "discount_non_negative", "orders", "discount_cents >= 0", schema="orders"
    )
    op.create_check_constraint(
        "discount_within_subtotal",
        "orders",
        "discount_cents <= subtotal_cents",
        schema="orders",
    )


def downgrade() -> None:
    """Revert this migration."""

    op.drop_constraint("ck_orders_discount_within_subtotal", "orders", schema="orders")
    op.drop_constraint("ck_orders_discount_non_negative", "orders", schema="orders")
    op.drop_constraint("ck_orders_total_is_sum_of_parts", "orders", schema="orders")
    op.create_check_constraint(
        "total_is_sum_of_parts",
        "orders",
        "total_cents = subtotal_cents + tax_cents + shipping_cents",
        schema="orders",
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'shipped_at', schema='orders')
    op.drop_column('orders', 'tracking_number', schema='orders')
    op.drop_column('orders', 'carrier', schema='orders')
    op.drop_column('orders', 'discount_code', schema='orders')
    op.drop_column('orders', 'discount_cents', schema='orders')
    op.drop_index(op.f('ix_orders_discount_codes_code'), table_name='discount_codes', schema='orders')
    op.drop_index('ix_discount_codes_active', table_name='discount_codes', schema='orders')
    op.drop_table('discount_codes', schema='orders')
    # ### end Alembic commands ###
