"""initial orders schema

Revision ID: f3e4ad63a25a
Revises: 
Created: 2026-09-12 10:16:28.724115+00:00

Checklist before merging a migration:
  * Is `downgrade()` correct? You will want it during an incident.
  * Does it lock a large table? ALTER TABLE ... ADD COLUMN with a non-null
    default rewrites the whole table on older Postgres; add the column
    nullable, backfill in batches, then set NOT NULL.
  * Does it drop or rename anything the running code still reads? Deploy the
    code change first, the schema change second.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'f3e4ad63a25a'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carts',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('session_token_hash', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='open', nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='usd', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint("status IN ('open', 'converted', 'abandoned')", name=op.f('ck_carts_status_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_carts')),
    sa.UniqueConstraint('session_token_hash', name=op.f('uq_carts_session_token_hash')),
    schema='orders'
    )
    op.create_index('ix_carts_user_status', 'carts', ['user_id', 'status'], unique=False, schema='orders')
    op.create_index(op.f('ix_orders_carts_user_id'), 'carts', ['user_id'], unique=False, schema='orders')
    op.create_table('orders',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_number', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', postgresql.CITEXT(), nullable=False),
    sa.Column('status', sa.String(length=30), server_default='pending_payment', nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('tax_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('shipping_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='usd', nullable=False),
    sa.Column('shipping_address', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('billing_address', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('payment_intent_id', sa.String(length=120), nullable=True),
    sa.Column('cart_id', sa.UUID(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint("status IN ('pending_payment', 'paid', 'fulfilled', 'delivered', 'cancelled', 'refunded')", name=op.f('ck_orders_status_valid')),
    sa.CheckConstraint('subtotal_cents >= 0', name=op.f('ck_orders_subtotal_non_negative')),
    sa.CheckConstraint('total_cents = subtotal_cents + tax_cents + shipping_cents', name=op.f('ck_orders_total_is_sum_of_parts')),
    sa.CheckConstraint('total_cents >= 0', name=op.f('ck_orders_total_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders')),
    sa.UniqueConstraint('payment_intent_id', name=op.f('uq_orders_payment_intent_id')),
    schema='orders'
    )
    op.create_index(op.f('ix_orders_orders_order_number'), 'orders', ['order_number'], unique=True, schema='orders')
    op.create_index(op.f('ix_orders_orders_user_id'), 'orders', ['user_id'], unique=False, schema='orders')
    op.create_index('ix_orders_status_created', 'orders', ['status', 'created_at'], unique=False, schema='orders')
    op.create_index('ix_orders_user_created', 'orders', ['user_id', 'created_at'], unique=False, schema='orders')
    op.create_table('cart_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cart_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('quantity <= 100', name=op.f('ck_cart_items_quantity_reasonable')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_cart_items_quantity_positive')),
    sa.ForeignKeyConstraint(['cart_id'], ['orders.carts.id'], name=op.f('fk_cart_items_cart_id_carts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cart_items')),
    sa.UniqueConstraint('cart_id', 'variant_id', name='uq_cart_items_cart_id_variant'),
    schema='orders'
    )
    op.create_table('order_events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], name=op.f('fk_order_events_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_events')),
    schema='orders'
    )
    op.create_index('ix_order_events_order_time', 'order_events', ['order_id', 'created_at'], unique=False, schema='orders')
    op.create_table('order_items',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('variant_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('product_title', sa.String(length=200), nullable=False),
    sa.Column('product_slug', sa.String(length=160), nullable=True),
    sa.Column('variant_name', sa.String(length=160), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_items_quantity_positive')),
    sa.CheckConstraint('total_cents = unit_price_cents * quantity', name=op.f('ck_order_items_line_total_consistent')),
    sa.CheckConstraint('unit_price_cents >= 0', name=op.f('ck_order_items_unit_price_non_negative')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items')),
    schema='orders'
    )
    op.create_index('ix_order_items_order', 'order_items', ['order_id'], unique=False, schema='orders')
    op.create_index('ix_order_items_variant', 'order_items', ['variant_id'], unique=False, schema='orders')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_order_items_variant', table_name='order_items', schema='orders')
    op.drop_index('ix_order_items_order', table_name='order_items', schema='orders')
    op.drop_table('order_items', schema='orders')
    op.drop_index('ix_order_events_order_time', table_name='order_events', schema='orders')
    op.drop_table('order_events', schema='orders')
    op.drop_table('cart_items', schema='orders')
    op.drop_index('ix_orders_user_created', table_name='orders', schema='orders')
    op.drop_index('ix_orders_status_created', table_name='orders', schema='orders')
    op.drop_index(op.f('ix_orders_orders_user_id'), table_name='orders', schema='orders')
    op.drop_index(op.f('ix_orders_orders_order_number'), table_name='orders', schema='orders')
    op.drop_table('orders', schema='orders')
    op.drop_index(op.f('ix_orders_carts_user_id'), table_name='carts', schema='orders')
    op.drop_index('ix_carts_user_status', table_name='carts', schema='orders')
    op.drop_table('carts', schema='orders')
    # ### end Alembic commands ###
