"""initial catalog schema

Revision ID: 8394c108d215
Revises: 
Created: 2026-09-12 10:10:32.950254+00:00

Checklist before merging a migration:
  * Is `downgrade()` correct? You will want it during an incident.
  * Does it lock a large table? ALTER TABLE ... ADD COLUMN with a non-null
    default rewrites the whole table on older Postgres; add the column
    nullable, backfill in batches, then set NOT NULL.
  * Does it drop or rename anything the running code still reads? Deploy the
    code change first, the schema change second.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '8394c108d215'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_categories_slug_format')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_categories_slug'), 'categories', ['slug'], unique=True, schema='catalog')
    op.create_table('products',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('slug', sa.String(length=160), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('subtitle', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint("slug ~ '^[a-z0-9]+(-[a-z0-9]+)*$'", name=op.f('ck_products_slug_format')),
    sa.CheckConstraint("status IN ('draft', 'active', 'archived')", name=op.f('ck_products_status_valid')),
    sa.ForeignKeyConstraint(['category_id'], ['catalog.categories.id'], name=op.f('fk_products_category_id_categories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_products_slug'), 'products', ['slug'], unique=True, schema='catalog')
    op.create_index('ix_products_status_category', 'products', ['status', 'category_id', 'position'], unique=False, schema='catalog')
    op.create_table('product_variants',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('compare_at_price_cents', sa.Integer(), nullable=True),
    sa.Column('currency', sa.String(length=3), server_default='usd', nullable=False),
    sa.Column('inventory_quantity', sa.Integer(), server_default='0', nullable=False),
    sa.Column('track_inventory', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('weight_grams', sa.Integer(), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('char_length(currency) = 3', name=op.f('ck_product_variants_currency_iso_4217')),
    sa.CheckConstraint('inventory_quantity >= 0', name=op.f('ck_product_variants_inventory_non_negative')),
    sa.CheckConstraint('price_cents >= 0', name=op.f('ck_product_variants_price_non_negative')),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], name=op.f('fk_product_variants_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_variants')),
    schema='catalog'
    )
    op.create_index(op.f('ix_catalog_product_variants_sku'), 'product_variants', ['sku'], unique=True, schema='catalog')
    op.create_index('ix_product_variants_product', 'product_variants', ['product_id', 'position'], unique=False, schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_variants_product', table_name='product_variants', schema='catalog')
    op.drop_index(op.f('ix_catalog_product_variants_sku'), table_name='product_variants', schema='catalog')
    op.drop_table('product_variants', schema='catalog')
    op.drop_index('ix_products_status_category', table_name='products', schema='catalog')
    op.drop_index(op.f('ix_catalog_products_slug'), table_name='products', schema='catalog')
    op.drop_table('products', schema='catalog')
    op.drop_index(op.f('ix_catalog_categories_slug'), table_name='categories', schema='catalog')
    op.drop_table('categories', schema='catalog')
    # ### end Alembic commands ###
