"""product reviews and ratings

Revision ID: 857634f452a7
Revises: 4b9dc99e6f27
Created: 2026-09-13 13:40:40.540882+00:00

Checklist before merging a migration:
  * Is `downgrade()` correct? You will want it during an incident.
  * Does it lock a large table? ALTER TABLE ... ADD COLUMN with a non-null
    default rewrites the whole table on older Postgres; add the column
    nullable, backfill in batches, then set NOT NULL.
  * Does it drop or rename anything the running code still reads? Deploy the
    code change first, the schema change second.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '857634f452a7'
down_revision: str | None = '4b9dc99e6f27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product_reviews',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=160), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_verified_purchase', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='published', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint("status IN ('published', 'hidden')", name=op.f('ck_product_reviews_status_valid')),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name=op.f('ck_product_reviews_rating_in_range')),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], name=op.f('fk_product_reviews_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_reviews')),
    sa.UniqueConstraint('product_id', 'user_id', name='uq_product_reviews_product_id_user'),
    schema='catalog'
    )
    op.create_index('ix_product_reviews_product_created', 'product_reviews', ['product_id', 'created_at'], unique=False, schema='catalog')
    op.create_index('ix_product_reviews_status', 'product_reviews', ['status'], unique=False, schema='catalog')
    op.add_column('products', sa.Column('rating_count', sa.Integer(), server_default='0', nullable=False), schema='catalog')
    op.add_column('products', sa.Column('rating_sum', sa.Integer(), server_default='0', nullable=False), schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'rating_sum', schema='catalog')
    op.drop_column('products', 'rating_count', schema='catalog')
    op.drop_index('ix_product_reviews_status', table_name='product_reviews', schema='catalog')
    op.drop_index('ix_product_reviews_product_created', table_name='product_reviews', schema='catalog')
    op.drop_table('product_reviews', schema='catalog')
    # ### end Alembic commands ###
