"""product images and media library

Revision ID: 4b9dc99e6f27
Revises: 8394c108d215
Created: 2026-09-13 13:21:55.247547+00:00

Checklist before merging a migration:
  * Is `downgrade()` correct? You will want it during an incident.
  * Does it lock a large table? ALTER TABLE ... ADD COLUMN with a non-null
    default rewrites the whole table on older Postgres; add the column
    nullable, backfill in batches, then set NOT NULL.
  * Does it drop or rename anything the running code still reads? Deploy the
    code change first, the schema change second.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


revision: str = '4b9dc99e6f27'
down_revision: str | None = '8394c108d215'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_assets',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('filename', sa.String(length=140), nullable=False),
    sa.Column('thumb_filename', sa.String(length=140), nullable=False),
    sa.Column('original_name', sa.String(length=260), nullable=True),
    sa.Column('content_type', sa.String(length=60), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint('width > 0 AND height > 0', name=op.f('ck_media_assets_dimensions_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_assets')),
    sa.UniqueConstraint('filename', name=op.f('uq_media_assets_filename')),
    schema='catalog'
    )
    op.create_index('ix_media_assets_created', 'media_assets', ['created_at'], unique=False, schema='catalog')
    op.create_table('product_images',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('media_id', sa.UUID(), nullable=False),
    sa.Column('alt', sa.String(length=300), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.ForeignKeyConstraint(['media_id'], ['catalog.media_assets.id'], name=op.f('fk_product_images_media_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['catalog.products.id'], name=op.f('fk_product_images_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product_images')),
    sa.UniqueConstraint('product_id', 'media_id', name='uq_product_images_product_id_media'),
    schema='catalog'
    )
    op.create_index('ix_product_images_product_position', 'product_images', ['product_id', 'position'], unique=False, schema='catalog')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_product_images_product_position', table_name='product_images', schema='catalog')
    op.drop_table('product_images', schema='catalog')
    op.drop_index('ix_media_assets_created', table_name='media_assets', schema='catalog')
    op.drop_table('media_assets', schema='catalog')
    # ### end Alembic commands ###
