"""Database tables owned by the auth service (schema ``auth``).

Five tables, each with one job:

* ``users``                  — the account itself.
* ``refresh_tokens``         — one row per active session, revocable.
* ``password_reset_tokens``  — single-use, short-lived reset links.
* ``login_attempts``         — the record brute-force lockout is computed from.
* ``audit_events``           — an append-only trail of security-relevant actions.

Storage rules applied throughout:

* No plaintext secret is ever stored. Passwords are Argon2id hashes; tokens are
  SHA-256 digests. A stolen database backup yields no working credentials.
* Timestamps are ``timestamptz`` and generated by Postgres. Naive timestamps
  are the reason so many systems have off-by-one-hour bugs twice a year.
* Foreign keys cascade on delete, so "delete my account" genuinely removes the
  sessions and reset tokens too — which is what a GDPR erasure request requires.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from ecom_shared.db import declarative_base_for, utcnow_sql
from sqlalchemy import (
    Boolean,
    CheckConstraint,
    DateTime,
    ForeignKey,
    Index,
    String,
    Text,
    func,
)
from sqlalchemy.dialects.postgresql import CITEXT, INET, JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

Base = declarative_base_for("auth")

#: Every role the system recognises. Enforced by a CHECK constraint rather than
#: a Postgres ENUM: adding a value to an ENUM requires a migration that locks
#: the type, while a CHECK is a cheap constraint swap.
VALID_ROLES = ("customer", "admin")


class User(Base):
    """A person with an account.

    Attributes:
        id: Primary key. A UUID rather than a serial integer, because
            sequential IDs let anyone who sees ``/users/41`` infer both how many
            customers you have and what the neighbouring IDs are.
        email: Case-insensitive, unique. `CITEXT` means the unique index treats
            ``Alice@x.com`` and ``alice@x.com`` as the same address, which is
            what users assume and what stops duplicate-account confusion.
        password_hash: Argon2id encoded hash. Never the password.
        role: ``customer`` or ``admin``, constrained at the database level.
        is_active: Soft disable. Deactivating preserves order history, which
            you are legally required to retain for tax purposes, while blocking
            sign-in immediately.
        email_verified_at: When ownership of the address was confirmed.
        last_login_at: Surfaced in the admin console and useful for spotting a
            dormant account that suddenly becomes active.
    """

    __tablename__ = "users"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    email: Mapped[str] = mapped_column(CITEXT, nullable=False, unique=True, index=True)
    password_hash: Mapped[str] = mapped_column(Text, nullable=False)
    full_name: Mapped[str | None] = mapped_column(String(200))
    role: Mapped[str] = mapped_column(String(20), nullable=False, server_default="customer")
    is_active: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")

    email_verified_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    last_login_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=utcnow_sql()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=utcnow_sql(),
        onupdate=func.now(),
    )

    refresh_tokens: Mapped[list[RefreshToken]] = relationship(
        back_populates="user", cascade="all, delete-orphan"
    )

    __table_args__ = (
        CheckConstraint(f"role IN {VALID_ROLES}", name="role_valid"),
        # Rejects '', 'nope' and 'a@b' at the storage layer. Application-level
        # validation can be bypassed by a bad migration or a manual INSERT;
        # a constraint cannot.
        CheckConstraint(
            "email ~ '^[^@[:space:]]+@[^@[:space:]]+\\.[^@[:space:]]+$'", name="email_shape"
        ),
    )

    def __repr__(self) -> str:
        """Debug representation. Deliberately omits the email.

        Repr output ends up in exception messages and log lines, and an email
        address is personal data — it should appear only where we put it on
        purpose, not incidentally in a traceback.
        """
        return f"<User id={self.id} role={self.role} active={self.is_active}>"


class RefreshToken(Base):
    """One active (or formerly active) session.

    Refresh tokens are stored so that sessions are *revocable*. Access tokens
    are self-contained JWTs and cannot be withdrawn before they expire, which
    is precisely why they only live 15 minutes; the refresh token is the part
    with real staying power, so it is the part we keep control of.

    **Rotation with reuse detection.** Every refresh consumes the old token and
    issues a new one, linked via `rotated_to_id`. If a token that has already
    been rotated is presented again, exactly one of two things happened: the
    legitimate client replayed a request, or an attacker is using a stolen
    copy. We cannot tell which, so we assume the worst and revoke the entire
    chain for that user — forcing a fresh sign-in. This is the standard
    detection mechanism for stolen refresh tokens, and it turns silent,
    indefinite account access into a single failed request.

    Attributes:
        token_hash: SHA-256 of the token. The token itself exists only in the
            user's cookie.
        expires_at: Absolute expiry, independent of revocation.
        revoked_at: Set on logout, on rotation, or on reuse detection.
        rotated_to_id: The token that replaced this one, forming the chain.
        user_agent: Truncated client string, so "Chrome on Windows" is
            recognisable in the session list.
        ip_address: Source address, for the same reason.
    """

    __tablename__ = "refresh_tokens"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    token_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)

    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    revoked_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    rotated_to_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("refresh_tokens.id", ondelete="SET NULL")
    )

    user_agent: Mapped[str | None] = mapped_column(String(400))
    ip_address: Mapped[str | None] = mapped_column(INET)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=utcnow_sql()
    )

    user: Mapped[User] = relationship(back_populates="refresh_tokens")

    __table_args__ = (
        # Serves both "list this user's sessions" and the bulk revoke on reuse
        # detection, which is the path that must be fast because it runs during
        # a suspected compromise.
        Index("ix_refresh_tokens_user_active", "user_id", "revoked_at"),
        Index("ix_refresh_tokens_expires_at", "expires_at"),
    )

    @property
    def is_usable(self) -> bool:
        """Whether this token can still be exchanged. Not a security check.

        Expiry is compared in Python for convenience in the admin UI; the
        authoritative check happens in SQL inside the refresh transaction,
        where it cannot race with a concurrent revocation.
        """
        from datetime import UTC

        return self.revoked_at is None and self.expires_at > datetime.now(UTC)


class PasswordResetToken(Base):
    """A single-use, short-lived password reset link.

    Attributes:
        token_hash: SHA-256 of the token emailed to the user.
        used_at: Set the moment the token is redeemed. A reset link that works
            twice is a reset link an attacker can reuse after reading the
            victim's inbox once.
    """

    __tablename__ = "password_reset_tokens"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    user_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="CASCADE"), nullable=False
    )
    token_hash: Mapped[str] = mapped_column(String(64), nullable=False, unique=True)
    expires_at: Mapped[datetime] = mapped_column(DateTime(timezone=True), nullable=False)
    used_at: Mapped[datetime | None] = mapped_column(DateTime(timezone=True))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=utcnow_sql()
    )

    __table_args__ = (Index("ix_password_reset_tokens_user_id", "user_id"),)


class LoginAttempt(Base):
    """One sign-in attempt, successful or not.

    Two purposes:

    1. **Lockout.** Counting recent failures for an address is how brute force
       is stopped. Keyed on email rather than IP, because a distributed
       attacker rotates addresses trivially while the target email is fixed.
    2. **Forensics.** After an incident, this table answers "when did they get
       in, and from where".

    Attributes:
        email: Stored even when no such user exists, so attempts against
            non-existent accounts are still visible.
        succeeded: Outcome.
        failure_reason: Coarse category (``bad_password``, ``locked``,
            ``inactive``). Never contains the submitted password.
    """

    __tablename__ = "login_attempts"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    email: Mapped[str] = mapped_column(CITEXT, nullable=False)
    ip_address: Mapped[str | None] = mapped_column(INET)
    user_agent: Mapped[str | None] = mapped_column(String(400))
    succeeded: Mapped[bool] = mapped_column(Boolean, nullable=False)
    failure_reason: Mapped[str | None] = mapped_column(String(50))
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=utcnow_sql()
    )

    __table_args__ = (
        # The lockout query is "failures for this email since T", so the index
        # is ordered to match and answers it with a single range scan.
        Index("ix_login_attempts_email_time", "email", "created_at"),
        Index("ix_login_attempts_ip_time", "ip_address", "created_at"),
    )


class AuditEvent(Base):
    """Append-only record of security-relevant actions.

    Written whenever something happens that you would want explained later:
    a role change, a deactivation, a password reset, an admin viewing customer
    data. Nothing here is ever updated or deleted by application code — an
    audit log you can edit is not an audit log.

    Attributes:
        actor_user_id: Who did it. ``NULL`` for unauthenticated actions such as
            a password-reset request.
        action: Dotted verb, e.g. ``user.role_changed``.
        target_type: The kind of object acted on, e.g. ``"user"``.
        target_id: Its identifier, as text so it can reference any service.
        event_metadata: Structured context. Must never contain a credential;
            for a role change it holds ``{"from": "customer", "to": "admin"}``.
    """

    __tablename__ = "audit_events"

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), primary_key=True, server_default=func.gen_random_uuid()
    )
    actor_user_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True), ForeignKey("users.id", ondelete="SET NULL")
    )
    action: Mapped[str] = mapped_column(String(100), nullable=False)
    target_type: Mapped[str | None] = mapped_column(String(50))
    target_id: Mapped[str | None] = mapped_column(String(100))
    ip_address: Mapped[str | None] = mapped_column(INET)
    user_agent: Mapped[str | None] = mapped_column(String(400))
    # Named `event_metadata` because `metadata` is reserved on a SQLAlchemy
    # declarative class; the column itself is plain `metadata` in Postgres.
    event_metadata: Mapped[dict] = mapped_column(
        "metadata", JSONB, nullable=False, server_default="{}"
    )
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=utcnow_sql()
    )

    __table_args__ = (
        Index("ix_audit_events_actor_time", "actor_user_id", "created_at"),
        Index("ix_audit_events_action_time", "action", "created_at"),
    )
