"""initial analytics schema

Revision ID: bed933649163
Revises: 
Created: 2026-09-12 10:24:56.911195+00:00

Checklist before merging a migration:
  * Is `downgrade()` correct? You will want it during an incident.
  * Does it lock a large table? ALTER TABLE ... ADD COLUMN with a non-null
    default rewrites the whole table on older Postgres; add the column
    nullable, backfill in batches, then set NOT NULL.
  * Does it drop or rename anything the running code still reads? Deploy the
    code change first, the schema change second.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = 'bed933649163'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_rollups',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('day', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('event_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unique_sessions', sa.Integer(), server_default='0', nullable=False),
    sa.Column('unique_visitors', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_rollups')),
    schema='analytics'
    )
    op.create_index('ix_daily_rollups_day_type', 'daily_rollups', ['day', 'event_type'], unique=True, schema='analytics')
    op.create_table('events',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('session_hash', sa.String(length=64), nullable=False),
    sa.Column('visitor_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('path', sa.String(length=500), nullable=True),
    sa.Column('referrer_host', sa.String(length=200), nullable=True),
    sa.Column('device_type', sa.String(length=20), nullable=True),
    sa.Column('browser_family', sa.String(length=40), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text("timezone('utc', now())"), nullable=False),
    sa.CheckConstraint("event_type IN ('page_view', 'product_view', 'add_to_cart', 'remove_from_cart', 'checkout_started', 'checkout_completed', 'search', 'signup', 'login')", name=op.f('ck_events_event_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    schema='analytics'
    )
    op.create_index('ix_events_session', 'events', ['session_hash', 'occurred_at'], unique=False, schema='analytics')
    op.create_index('ix_events_time', 'events', ['occurred_at'], unique=False, schema='analytics')
    op.create_index('ix_events_type_time', 'events', ['event_type', 'occurred_at'], unique=False, schema='analytics')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_type_time', table_name='events', schema='analytics')
    op.drop_index('ix_events_time', table_name='events', schema='analytics')
    op.drop_index('ix_events_session', table_name='events', schema='analytics')
    op.drop_table('events', schema='analytics')
    op.drop_index('ix_daily_rollups_day_type', table_name='daily_rollups', schema='analytics')
    op.drop_table('daily_rollups', schema='analytics')
    # ### end Alembic commands ###
